server {

    listen 8080;

    root ./www;

    location /images {

        root ./assets;

        methods GET POST;

    }

    location /upload {

        root ./23;

        methods DELETE;

    }
}

# server {
#     listen  880;
#     root ./www;
#     index index.html;
# }